package com.kk.tajniacy.utils;

import lombok.experimental.UtilityClass;

import java.util.List;

@UtilityClass
public class Words {
    public static final List<String> words = List.of(
            "AFRYKA","AGENT","POWIETRZE","OBCY","ALPY","AMAZONKA","KARETKA","AMERYKA","ANIOŁ","ANTARKTYDA",
            "JABŁKO","RAMIĘ","ATLANTYDA","AUSTRALIA","AZTEK","PLECY","PIŁKA","ZESPÓŁ","BANK","BAR","KORA","NIETOPERZ",
            "BATERIA","PLAŻA","NIEDŹWIEDŹ","POKONAĆ","ŁÓŻKO","PEKIN","DZWON","PASEK","BERLIN","BERMUDY","JAGODA",
            "RACHUNEK","BLOK","DESKA","ŚRUBA","BOMBA","OBLIGACJA","BUM","BAGAŻNIK","BUTELKA","UKŁON","SKRZYNKA","MOST",
            "SZCZOTKA","BRYKNIĘCIE","BAWÓŁ","BŁĄD","DĄBRÓWKA","PRZYCISK","ŁYDKA","KANADA","CZAPKA","STOLICA","SAMOCHÓD",
            "KARTA","MARCHEWKA","KASYNO","RZUCAĆ","KOT","KOMÓRKA","CENTAUR","CENTRUM","KRZESŁO","ZMIANA","OPŁATA",
            "SPRAWDZAĆ","SKRZYNIA","PISKLĘ","CHINY","CZEKOLADA","KOŚCIÓŁ","OKRĄG","KLIF","PŁASZCZ","KLUB","KOD",
            "PRZEZIĘBIENIE","KOMICZNY","MIESZANINA","KONCERT","KONDUKTOR","KONTRAKT","GOTOWAĆ","MIEDŹ","BAWEŁNA","SĄD",
            "POKRYWA","DŹWIG","ROZBIĆ SIĘ","KRYKIET","KRZYŻ","KORONA","CYKL","CZECH","TANIEC","DATA","DZIEŃ","ŚMIERĆ",
            "TALIA KART","STOPIEŃ","DIAMENT","KOSTKA DO GRY","DINOZAUR","CHOROBA","LEKARZ","PIES","PROJEKT","SMOK",
            "SUKIENKA","WIERTARKA","KROPLA","KACZKA","KRASNOLUD","ORZEŁ","EGIPT","AMBASADA","SILNIK","ANGLIA","EUROPA",
            "OKO","TWARZ","SPRAWIEDLIWY","SPADEK","WENTYLATOR","PŁOT","POLE","WOJOWNIK","POSTAĆ","PLIK","FILM","OGIEŃ",
            "RYBA","FLET PROSTY","LATAĆ","STOPA","ZMUSZAĆ","LAS","WIDELEC","FRANCJA","GRA","GAZ","GENIUSZ","NIEMCY",
            "DUCH","OGROMNY","SZKŁO","RĘKAWICA","ZŁOTO","WDZIĘK","TRAWKA","GRECJA","ZIELONY","GRUNT","SZYNKA","RĘKA",
            "JASTRZĄB","GŁOWA","SERCE","ŚMIGŁOWIEC","HIMALAJE","OTWÓR","HOLLYWOOD","MIÓD","KAPTUR","HAK","KLAKSON",
            "KOŃ","PODKOWA","SZPITAL","HOTEL","LÓD","LODY","INDIE","ŻELAZO","KOŚĆ SŁONIOWA","JACEK","DŻEM","STRUMIEŃ",
            "JOWISZ","KANGUR","KECZUP","KLUCZ","DZIECKO","KRÓL","KIWI","NÓŻ","RYCERZ","LABORATORIUM","OKRĄŻENIE",
            "LASER","PRAWNIK","OŁÓW","CYTRYNOWY","KRASNOLUDEK","ŻYCIE","ŚWIATŁO","LIMUZYNA","LINIA","POŁĄCZYĆ","LEW",
            "ŚMIECI","LOCH NESS","ZAMEK","DZIENNIK","LONDYN","SZCZĘŚCIE","POCZTA","MAMUT","KLON","MARMUR","MARSZ",
            "MASA","DOPASOWANIE","RTĘĆ","MEKSYK","MIKROSKOP","MILIONER","MOJE","MENNICA","POCISK","MODEL","KRET",
            "KSIĘŻYC","MOSKWA","UCHWYT","MYSZ","USTA","KUBEK","GWÓŹDŹ","IGŁA","INTERNET","NOWY JORK","NOC","NINJA",
            "UWAGA","POWIEŚĆ","PIELĘGNIARKA","ORZECH","OŚMIORNICA","OLEJ","OLIWA","OLIMPUS","OPERA","POMARAŃCZOWY",
            "ORGAN","PALMA","PATELNIA","SPODNIE","PAPIER","SPADOCHRON","PARK","CZĘŚĆ","PRZECHODZIĆ","PASTA","PINGWIN",
            "FENIKS","FORTEPIAN","CIASTO","PILOT","SZPILKA","RURA","PIRAT","PISTOLET","DÓŁ","POZIOM","SAMOLOT",
            "PLASTIKOWY","TALERZ","DZIOBAK","BAWIĆ SIĘ","INTRYGOWAĆ","PUNKT","ZATRUĆ","POLAK","POLICJA","BASEN",
            "PORT","POCZTA","FUNT","NACIŚNIJ","KSIĘŻNICZKA","DYNIA","UCZEŃ","PIRAMIDA","KRÓLOWA","KRÓLIK","RAKIETA",
            "PROMIEŃ","REWOLUCJA","DZWONIĆ","RUDZIK","ROBOT","GŁAZ","RZYM","ŹRÓDŁO","RÓŻA","RULETKA","OKRĄGŁY","WIERSZ",
            "LINIJKA","SATELITA","SATURN","SKALA","SZKOŁA","NAUKOWIEC","SKORPION","EKRAN","NUREK","FOKA","SERWER","CIEŃ",
            "Szekspir","REKIN","STATEK","BUT","SKLEP","STRZAŁ","TONĄĆ","DRAPACZ CHMUR","POŚLIZG","ŚLIMAK","PRZEMYTNIK",
            "ŚNIEG","BAŁWAN","SKARPETKA","ŻOŁNIERZ","DUSZA","DŹWIĘK","PRZESTRZEŃ","ZAKLĘCIE","PAJĄK","KOLEC","KRĘGOSŁUP",
            "MIEJSCE","WIOSNA","SZPIEG","KWADRAT","STADION","PERSONEL","GWIAZDA","PAŃSTWO","STICK","ZBIORY","SŁOMA",
            "STRUMIEŃ","STRAJK","STRUNOWY","POD","GARNITUR","SUPERBOHATER","HUŚTAĆ SIĘ","PRZEŁĄCZNIK","TABELA","TABLET",
            "ETYKIETKA","OGON","UZYSKIWAĆ","NAUCZYCIEL","TELESKOP","ŚWIĄTYNIA","TEATR","ZŁODZIEJ","KCIUK","KLESZCZ",
            "KRAWAT","CZAS","TOKIO","ZĄB","LATARKA","WIEŻA","ŚCIEŻKA","POCIĄG","TRÓJKĄT","WYJAZD","PIEŃ","RURA","INDYK",
            "WŁAŚCICIEL ZAKŁADU POGRZEBOWEGO","JEDNOROŻEC","PRÓŻNIA","AWANGARDA","WETERYNARZ","BUDZIĆ","ŚCIANA","WOJNA",
            "PRALKA","WASZYNGTON","ZEGAREK","WODA","FALA","SIEĆ","DOBRZE","WIELORYB","BICZ","WIATR","CZAROWNICA","ROBAK",
            "DZIEDZINIEC"
    );
}
